### ISSUE TITLE
why REST service of azure file share does not have support for either optimistic locking or pessimistic locking?

### ISSUE THREAD

**Issue by jainrocks** [Azure-Samples/azure-sdk-for-java-storage-blob-upload-download#11]
why REST service of azure file share does not have support for either optimistic locking or pessimistic locking?

**Comment by jongio** [comment]
@jainrocks - Can you add more info about your question?  Where are you seeing this?

**Comment by jongio** [comment]
Closing for now. Please reopen if you would like to discuss.  Thanks
